name: dart_dependency_injection
description: The most powerful dependency injection library for Dart.
version: 1.2.0
homepage: https://github.com/yiiim/dart_dependency_injection

topics:
 - dependency-injection

environment:
  sdk: ">=2.17.6 <4.0.0"

dependencies:
  collection: ^1.16.0
  meta: ^1.7.0
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
